name: sportsoccer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.0
  cloud_firestore: ^5.4.4
  firebase_database: ^11.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - imagen/logo.webp