// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYpTBlDTvdTFmMN3hHplsXZAUOav4PXEY',
    appId: '1:424364427694:web:222c66c601f0cf96b0a03f',
    messagingSenderId: '424364427694',
    projectId: 'sportsoccer-1e252',
    authDomain: 'sportsoccer-1e252.firebaseapp.com',
    storageBucket: 'sportsoccer-1e252.firebasestorage.app',
    measurementId: 'G-1959CV3DVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuvGGcLcctKdkDmPc24TQTE-YowhEItTk',
    appId: '1:424364427694:android:1ac8730f90f0f5b0b0a03f',
    messagingSenderId: '424364427694',
    projectId: 'sportsoccer-1e252',
    storageBucket: 'sportsoccer-1e252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz0FH0r_cxERyRy1VxH-AbmRSErgiaxLU',
    appId: '1:424364427694:ios:0be7b8e9b0e767ceb0a03f',
    messagingSenderId: '424364427694',
    projectId: 'sportsoccer-1e252',
    storageBucket: 'sportsoccer-1e252.firebasestorage.app',
    iosBundleId: 'com.example.sportsoccer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz0FH0r_cxERyRy1VxH-AbmRSErgiaxLU',
    appId: '1:424364427694:ios:0be7b8e9b0e767ceb0a03f',
    messagingSenderId: '424364427694',
    projectId: 'sportsoccer-1e252',
    storageBucket: 'sportsoccer-1e252.firebasestorage.app',
    iosBundleId: 'com.example.sportsoccer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYpTBlDTvdTFmMN3hHplsXZAUOav4PXEY',
    appId: '1:424364427694:web:b99f32d4c473e89db0a03f',
    messagingSenderId: '424364427694',
    projectId: 'sportsoccer-1e252',
    authDomain: 'sportsoccer-1e252.firebaseapp.com',
    storageBucket: 'sportsoccer-1e252.firebasestorage.app',
    measurementId: 'G-8PT4DPHYQP',
  );
}
